# Generated by Django 6.0.6 on 2026-07-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('quanity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=1000)),
                ('sales', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Mshakvum e'), ('delivery', 'janaparhin e'), ('ready', 'Avartvac e'), ('canceled', 'avartvac e')], default='pending')),
            ],
        ),
    ]
